package com.timetrack.app.data

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Checks the hand written migration against the schema Room generates.
 *
 * A migration that does not reproduce the expected schema makes Room throw the
 * first time the app opens an upgraded database, so the user sees a crash on
 * launch and the tracking history is stuck behind it. Nothing in the ordinary
 * test suite would catch that, because it only happens on a real v1 database.
 *
 * Rather than stand up an emulator for it, this reads the exported schema JSON
 * that `kspDebugKotlin` writes and compares its `createSql` statements with the
 * ones the migration runs. The schema files are committed, so the check works
 * offline and in CI.
 *
 * Test-only limitation: this proves the statements are the right ones, not that
 * SQLite executes them cleanly. Proving that needs a database, and is left to
 * an instrumented migration test.
 */
class MigrationsSchemaTest {

    @Test
    fun `the migration reproduces the schema Room expects for v2`() {
        val expected = statementsFromSchema(version = 2, table = "todos")

        assertEquals(
            "MIGRATION_1_2 no longer matches app/schemas/.../2.json. " +
                "Update the migration (or the schema) and keep the two in step.",
            expected.sorted(),
            MIGRATION_1_2_STATEMENTS.sorted(),
        )
    }

    @Test
    fun `the schema really does contain the todo table`() {
        // Guards the test above from passing vacuously if the extraction broke:
        // an empty expectation on both sides would compare equal.
        val expected = statementsFromSchema(version = 2, table = "todos")
        assertTrue("expected a CREATE TABLE statement", expected.any { it.contains("CREATE TABLE") })
        assertTrue("expected an index statement", expected.any { it.contains("CREATE INDEX") })
    }

    @Test
    fun `v1 predates the todo table`() {
        val v1 = statementsFromSchema(version = 1, table = "todos")
        assertTrue("v1 must not mention todos, or it was regenerated by mistake", v1.isEmpty())
    }

    /**
     * Pulls the `createSql` entries belonging to one table out of an exported
     * schema.
     *
     * The JSON is read as text and matched with regular expressions rather than
     * parsed: only single-line SQL strings are needed, and this keeps the test
     * free of a JSON dependency.
     *
     * Neither the table statement nor the index statements name the table
     * directly — Room writes the `` `${TABLE_NAME}` `` placeholder — so each
     * `createSql` is attributed to the nearest preceding `tableName`, which in
     * this generated format is always the entity that owns it.
     */
    private fun statementsFromSchema(version: Int, table: String): List<String> {
        val raw = schemaFile(version).readText()
        val owners = Regex("\"tableName\"\\s*:\\s*\"(.*?)\"").findAll(raw).toList()
        val statements = Regex("\"createSql\"\\s*:\\s*\"(.*?)\"").findAll(raw).toList()

        return statements
            .filter { statement ->
                val owner = owners.lastOrNull { it.range.first < statement.range.first }
                owner?.groupValues?.get(1) == table
            }
            .map { it.groupValues[1].replace("\${TABLE_NAME}", table) }
            .toList()
    }

    /**
     * Unit tests run with the module directory as the working directory, but the
     * exact one has changed between AGP versions, so both spellings are tried.
     */
    private fun schemaFile(version: Int): File {
        val relative = "schemas/com.timetrack.app.data.TimeTrackDatabase/$version.json"
        val candidates = listOf(File(relative), File("app/$relative"))
        return candidates.firstOrNull { it.isFile }
            ?: error(
                "找不到 $relative。先跑一次 :app:kspDebugKotlin 让 Room 导出 schema。" +
                    "已尝试：" + candidates.joinToString { it.absolutePath },
            )
    }
}
